### PR TITLE
Add remaining TSV sources

### PR DESCRIPTION
**Pull request by mnadareski**
Remove skeleton PSP DLC
Add PSP DLC.
Add PS3, PSP, and Vita themes.
Add PS3 avatars.
Add Vita updates.
Add PS4 (ALL).

Additionally, I named a lot of things to make them more discoverable in the future. Buttons, labels, and text boxes mostly. I can change those back if that's an issue.

**Note**: Most of the packages cannot be decrypted at this point, I even removed the code (temporarily) that checks for a valid RAP/zRif file so that even those will be downloaded.

### CODE REVIEW

**Comment by IcySon55** [comment]
Awww man, I just added game specific unpack directories (Vita only ATM) and it will definitely conflict with this. I was contemplating making all the same naming and code style changes but decided against it. :/

**Comment by mnadareski** [comment]
You can always rebase against my changes? Not sure how viable that is for you... or when this change will go in (if it ever goes in)

**Comment by IcySon55** [comment]
jhon gets busy it seems and doesn't work on NPS Browser often. I suppose we'll wait and see what he says about both. If he merges your changes in, I'll probably blow away my fork like last time and re-implement on the new code because you can't fix merge conflicts using the webUI and I'm not installing GitHub Desktop.

**Comment by TheRadziu** [comment]
@mnadareski hey. NoPayStation site now also generates tsv files for: PS3 avatars, ps4 games, ps4 dlcs, ps4 themes and ps4 updates, so these are currently missing as well.

**Comment by mnadareski** [comment]
...I guess I'll just add those too 👍

**Comment by IcySon55** [comment]
@mnadareski You think the options UI needs a bit of an overhaul? With so many TSVs it's getting a bit unwieldy. At the same time not all TSVs are treated equally in terms of unpacking, re: My per-game extraction PR #66. I also noticed that the new CheckBoxComboBox control has a focus bug where you have to click inside before any of the check boxes will react.

**Comment by mnadareski** [comment]
I have that in mind. When I update this PR, you can take a look. Honestly, my design sense is horrible, so any help is appreciated 👍

**Comment by IcySon55** [comment]
I'll likely drop my PR, pull yours onto my branch and make w/e tweaks I think will be good. My first thought was a DataGrid with a predetermined list of elements and just two columns. The first column being read-only and containing the expected TSV type followed by the editable TextBox in column 2. Thoughts?

**Comment by mnadareski** [comment]
ATM, my next commits will include just 2 columns of the input boxes so that the settings window goes wider. Honestly, it sounds like you know more about design than I do, so please, once I get this stuff working, go for it and just add whatever UI changes you need.

**Comment by mnadareski** [comment]
So, last 2 updates there belay something very odd about the NPS TSVs: most of the PS4 content is linked to a JSON file which ITSELF has the direct links to the package pieces. I got around this by downloading the JSON and then parsing that... though the side effect is that if you have all TSVs defined, you get a VERY slow loading process.

**Comment by mnadareski** [comment]
...And then another 2 because "not everything is a JSON" apparently.

**Comment by IcySon55** [comment]
Did you parse them manually or using a library? I'd recommend the lib router for speed.

**Comment by mnadareski** [comment]
The main dev had a JSON library already included in the code, so I just made use of that. Definitely no manual parsing of JSON here... I'm not quite that insane 👍

**Comment by jhonhenry10** [comment]
Who... lot of stuff happened here recently guys :) 

So... we need to rewrite tsv function: im thinking of downloading tsvs, and creating some kind of local cache, (with visited images and descriptions) with updating tsv once per few days or sth. Not downloading everything every start (this connects to ps4 jsons as well)

**Comment by jhonhenry10** [comment]
ideally would be external tool that will create json file with all content from all sources. then you will feed app with only one master url for that json

**Comment by IcySon55** [comment]
Personally, I think it's the database that needs to change. It should expose a webservice that allows nps browser to quickly download the list. The data itself should be curated to remove unnecessary complexity, like why are some entries json and others aren't? Leads me to think that none of them need to be json. Just that some are for no reason.

**Comment by TheRadziu** [comment]
@IcySon55 only ps4 games are in json in order to avoid multiple lines for single game (just like yakuza games for ps3). Additionally, they contain own hashes and more general information about a package.
Also, psndle gives json files for ps4 games, if I wanted to make 10 or so lines for big ps4 games (with every part in new line) that would mean more manual job for contributors.

**Comment by IcySon55** [comment]
In that case the json is fine. Though a webservice would be better.

One service to provide the list of games and a second one that provides the download links given a gameid.

Would speed things up and remove the need to cache locally. Though caching could still be added if the service also provides update dates.

**Comment by mnadareski** [comment]
Not sure how much it matters, but my commit here DOES separate out the JSON into component parts, currently named based on their offset.

**Comment by jhonhenry10** [comment]
Im thinking of moving whole content to local sqlite db, and sync this DB once a time with online sheets or on demand from menu. DB could have all content that is parsed at runtime now, so it will spead everything up.

**Comment by jhonhenry10** [comment]
Webservice is loot of works, and kills other apps that starts poping out.

**Pull request merged**
